# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./dev/php
        image: eggheads-code-style-php
        ports:
            - "9000:9000"
        # монтируем директорию с проектами
        volumes:
            - .:/var/www/
        # заходим в docker через: docker-compose exec -u www-data php bash
